runtime: python38
instance_class: F1
automatic_scaling:
  max_instances: 1
  min_instances: 0
handlers:
- url:  /doc_app/
  script: auto
- url: /
  static_files: static/index.html
  upload: static/index.html
- url: /
  static_dir: static
